-- ==== INSERTS FOR TABLE: MEASUREMENT_TYPE ====
INSERT INTO [MEASUREMENT_TYPE] ([MEASUREMENTNAME]) VALUES ( 'PRESSURE');
INSERT INTO [MEASUREMENT_TYPE] ([MEASUREMENTNAME]) VALUES ( 'LENGH');
INSERT INTO [MEASUREMENT_TYPE] ([MEASUREMENTNAME]) VALUES ( 'PARTICLESIZE');
INSERT INTO [MEASUREMENT_TYPE] ([MEASUREMENTNAME]) VALUES ( 'TEMPERATURE');
INSERT INTO [MEASUREMENT_TYPE] ([MEASUREMENTNAME]) VALUES ( 'FLOWRATE');
INSERT INTO [MEASUREMENT_TYPE] ([MEASUREMENTNAME]) VALUES ( 'VOLUME');
INSERT INTO [MEASUREMENT_TYPE] ([MEASUREMENTNAME]) VALUES ( 'TIME');
INSERT INTO [MEASUREMENT_TYPE] ([MEASUREMENTNAME]) VALUES ( 'INJECTIONCOUNT');


-- ==== INSERTS FOR TABLE: STATUS_MASTER ====
INSERT INTO [STATUS_MASTER] ([STATUSNAME]) VALUES ( 'AVAILABLE');
INSERT INTO [STATUS_MASTER] ([STATUSNAME]) VALUES ( 'CHECKED OUT');
INSERT INTO [STATUS_MASTER] ([STATUSNAME]) VALUES ( 'RETIRED');
INSERT INTO [STATUS_MASTER] ([STATUSNAME]) VALUES ( 'UNDER MAINTENANCE');


-- ==== INSERTS FOR TABLE: UNIT_MASTER ====
INSERT INTO [UNIT_MASTER] ([MEASUREMENTTYPEID],[UNITNAME],[UNITSYMBOL],[ISBASEUNIT]) VALUES ( 1, 'BAR', 'BAR', 1);
INSERT INTO [UNIT_MASTER] ([MEASUREMENTTYPEID],[UNITNAME],[UNITSYMBOL],[ISBASEUNIT]) VALUES ( 2, 'MILLIMETER', 'MM', 1);
INSERT INTO [UNIT_MASTER] ([MEASUREMENTTYPEID],[UNITNAME],[UNITSYMBOL],[ISBASEUNIT]) VALUES ( 3, 'MICROMETER', 'ΜM', 1);
INSERT INTO [UNIT_MASTER] ([MEASUREMENTTYPEID],[UNITNAME],[UNITSYMBOL],[ISBASEUNIT]) VALUES ( 4, 'DEGREE CELSIUS', '°C', 1);
INSERT INTO [UNIT_MASTER] ([MEASUREMENTTYPEID],[UNITNAME],[UNITSYMBOL],[ISBASEUNIT]) VALUES ( 5, 'MILLILITER PER MINUTE', 'ML/MIN', 1);
INSERT INTO [UNIT_MASTER] ([MEASUREMENTTYPEID],[UNITNAME],[UNITSYMBOL],[ISBASEUNIT]) VALUES ( 6, 'MILLILITER', 'ML', 1);
INSERT INTO [UNIT_MASTER] ([MEASUREMENTTYPEID],[UNITNAME],[UNITSYMBOL],[ISBASEUNIT]) VALUES ( 7, 'HOUR', 'HR', 1);
INSERT INTO [UNIT_MASTER] ([MEASUREMENTTYPEID],[UNITNAME],[UNITSYMBOL],[ISBASEUNIT]) VALUES ( 8, 'COUNT', 'COUNT', 1);


