// <auto-generated />
using System;
using COLManager.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COLManager.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COLManager.Web.Entities.AuditTrail", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditID");

                    b.ToTable("Audit_Trail", (string)null);
                });

            modelBuilder.Entity("COLManager.Web.Entities.ColumnMaintenanceLog", b =>
                {
                    b.Property<int>("MaintenanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceID"));

                    b.Property<int>("ColumnID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("PerformedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("MaintenanceID");

                    b.ToTable("Column_Maintenance_Log", (string)null);
                });

            modelBuilder.Entity("COLManager.Web.Entities.ColumnMaster", b =>
                {
                    b.Property<int>("ColumnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColumnID"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InstalledOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InternalDiameterMM")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("LengthMM")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("MaxPressureBar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ParticleSizeMicron")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("ProtocolID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RetiredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("TotalInjections")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRuntimeHours")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ColumnID");

                    b.HasIndex("ProtocolID");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Column_Master", (string)null);
                });

            modelBuilder.Entity("COLManager.Web.Entities.ColumnUsageLog", b =>
                {
                    b.Property<int>("UsageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageID"));

                    b.Property<int>("ColumnID")
                        .HasColumnType("int");

                    b.Property<decimal?>("FlowRateMLPerMin")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("InjectionVolumeML")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("MaxPressureObservedBar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NumberOfInjections")
                        .HasColumnType("int");

                    b.Property<decimal>("PostUseBackPressureBar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PreUseBackPressureBar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RuntimeHours")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("UsageID");

                    b.ToTable("Column_Usage_Log", (string)null);
                });

            modelBuilder.Entity("COLManager.Web.Entities.MeasurementType", b =>
                {
                    b.Property<int>("MeasurementTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasurementTypeID"));

                    b.Property<string>("MeasurementName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MeasurementTypeID");

                    b.HasIndex("MeasurementName")
                        .IsUnique();

                    b.ToTable("Measurement_Type", (string)null);
                });

            modelBuilder.Entity("COLManager.Web.Entities.Protocol", b =>
                {
                    b.Property<int>("ProtocolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProtocolID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxAllowedInjections")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxAllowedPressureBar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaxAllowedUsageHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("OperatingTemperatureC")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ProtocolName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProtocolID");

                    b.ToTable("Protocol", (string)null);
                });

            modelBuilder.Entity("COLManager.Web.Entities.StatusMaster", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("Status_Master", (string)null);
                });

            modelBuilder.Entity("COLManager.Web.Entities.UnitMaster", b =>
                {
                    b.Property<int>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitID"));

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<int>("MeasurementTypeID")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UnitID");

                    b.ToTable("Unit_Master", (string)null);
                });

            modelBuilder.Entity("COLManager.Web.Entities.ColumnMaster", b =>
                {
                    b.HasOne("COLManager.Web.Entities.Protocol", null)
                        .WithMany()
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
